[package]
name = "calllua"
version = "0.1.0"
edition = "2021"

[dependencies]
mlua = { version = "0.10.0", features = ["lua54", "vendored", "serialize"] }
serde = { version = "1.0.214", features = ["derive"] }
